spring.application.name=pdm-lifecycle-manager

# H2 Database
spring.datasource.url=jdbc:h2:mem:pdmdb
spring.datasource.driver-class-name=org.h2.Driver
spring.jpa.hibernate.ddl-auto=create-drop
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# See SQL queries in the console
spring.jpa.show-sql=true

# Disable security for now so it doesn't block you while developing
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration